[server]
headless = true
address = "0.0.0.0"
port = 5000
enableCORS = false
enableXsrfProtection = false

[theme]
base = "dark"
backgroundColor = "#000000"
secondaryBackgroundColor = "#050f05"
primaryColor = "#00ff88"
textColor = "#c8ffc8"
font = "monospace"
